/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.practices.app;

import java.practices.list.LinkedList;

import static java.practices.utilities.StringUtils.join;
import static java.practices.utilities.StringUtils.split;
import static java.practices.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
